# Generated by Django 5.1.3 on 2025-12-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='amount_change',
            new_name='total_discounts',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tendered_amount',
        ),
    ]
