# Generated by Django 5.1.3 on 2025-12-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_rename_amount_change_sales_total_discounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
