# Generated by Django 5.1.3 on 2025-12-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0003_sales_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
