# Generated by Django 5.1.3 on 2025-12-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_sales_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
