# Generated by Django 5.1.3 on 2025-12-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_cartitem_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='tqty',
            field=models.IntegerField(default=0),
        ),
    ]
