# Generated by Django 5.1.3 on 2025-12-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0006_sales_tqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='tcgst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='tsgst',
            field=models.FloatField(default=0),
        ),
    ]
