# Generated by Django 5.1.3 on 2025-12-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_alter_sales_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='ttax',
            field=models.FloatField(default=0),
        ),
    ]
