# Generated by Django 5.1.3 on 2025-12-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_sales_ttax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='uom',
            field=models.CharField(max_length=100),
        ),
    ]
