# Generated by Django 5.1.3 on 2025-12-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_alter_products_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dispercent',
            field=models.FloatField(default=0),
        ),
    ]
