# Generated by Django 5.1.3 on 2025-12-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_products_dispercent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='spin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sstatecode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
