# Generated by Django 5.1.3 on 2025-12-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0012_alter_customer_spin_alter_customer_sstatecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='taxable',
            field=models.FloatField(default=0),
        ),
    ]
